#pragma once

#define CONSOLELOGON_FOR_rs2  0
#define CONSOLELOGON_FOR_rs3  1
#define CONSOLELOGON_FOR_rs4  2
#define CONSOLELOGON_FOR_rs5  3
#define CONSOLELOGON_FOR_19h1 4
#define CONSOLELOGON_FOR_VB 5
#define CONSOLELOGON_FOR_MN 6
#define CONSOLELOGON_FOR_FE 7
#define CONSOLELOGON_FOR_CO 8
#define CONSOLELOGON_FOR_NI 9
#define CONSOLELOGON_FOR_ZN 10
#define CONSOLELOGON_FOR_GE 11

#ifndef CONSOLELOGON_FOR
//#define CONSOLELOGON_FOR CONSOLELOGON_FOR_NI
//#define CONSOLELOGON_FOR CONSOLELOGON_FOR_VB
#define CONSOLELOGON_FOR CONSOLELOGON_FOR_rs5
#endif
